SELECT LTRIM("    MY  SQL ES FACIL");
SELECT RTRIM("MY  SQL ES FACIL     ");
SELECT TRIM("    MY  SQL ES FACIL     ");

SELECT CONCAT(" MY  SQL ES FACIL ", "NO LO CREES");
SELECT UPPER("my sql es interesante");
SELECT LOWER("MY SQL ES INTERESANTE");
SELECT SUBSTRING("MY SQL ES INTERESANTE, NO LO CREES, ES CIERTO",14,4);
SELECT CONCAT(NOMBRE," ", DNI) FROM tabla_de_clientes;
SELECT NOMBRE, CONCAT(DIRECCION_1, ' ', BARRIO, ' ', CIUDAD, ' ', ESTADO) AS COMPLETO FROM tabla_de_clientes;

#DATE
SELECT curdate();
SELECT current_timestamp();
SELECT YEAR(current_timestamp());
SELECT month(current_timestamp());
SELECT monthname(current_timestamp());
SELECT DAY(current_timestamp());
SELECT DAYNAME(current_timestamp());
SELECT datediff(CURRENT_TIMESTAMP(), "2023-6-5") AS DIFERENCIA_DE_DIAS;
SELECT current_timestamp() AS DIA_HOY, 
DATE_SUB( current_timestamp(), INTERVAL 1 MONTH) AS RESULTADO;

SELECT DISTINCT FECHA_VENTA,
DAYNAME(FECHA_VENTA) AS DIA, monthname(FECHA_VENTA) AS MES, YEAR(FECHA_VENTA) AS AÑO
FROM facturas;

SELECT NOMBRE, TIMESTAMPDIFF(YEAR, FECHA_DE_NACIMIENTO, CURDATE()) AS    EDAD
FROM  tabla_de_clientes;
SELECT (34 +346 - 67)/15 * 29 AS RESULTADO;
SELECT ceiling(34.15555);
SELECT FLOOR(34.15555);
SELECT rand() AS RESULTADO; #RAND NUMERO ALEATORIO ENTRE 0 Y 1
SELECT round(25.545);
SELECT NUMERO, CANTIDAD, PRECIO, round(CANTIDAD*PRECIO,2) AS FACTURACION 
FROM items_facturas;
SELECT YEAR(FECHA_VENTA), FLOOR(SUM(IMPUESTO * (CANTIDAD * PRECIO))) 
AS RESULTADO
FROM facturas F
INNER JOIN items_facturas IFa ON F.NUMERO = IFa.NUMERO
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY YEAR(FECHA_VENTA);

SELECT current_timestamp() AS RESULTADO;
SELECT concat("LA FECHA Y HORA DE  HOY ES:  ", current_timestamp()) AS RESULTADO;
SELECT concat("lA FECHA Y EL HORARIO SON: " , 
DATE_FORMAT(current_timestamp(), "%W, %d %m %Y a las %T")) AS RESULTADO;

SELECT convert(23.45, CHAR) AS RESULTADO;
SELECT substring(convert(23.45, CHAR),2,2) AS RESULTADO;

SELECT CONCAT('El cliente ', TC.NOMBRE, ' facturó ', 
CONVERT(SUM(IFa.CANTIDAD * IFa.precio), CHAR(20))
 , ' en el año ', CONVERT(YEAR(F.FECHA_VENTA), CHAR(20))) AS FRASE FROM facturas F
INNER JOIN items_facturas IFa ON F.NUMERO = IFa.NUMERO
INNER JOIN tabla_de_clientes TC ON F.DNI = TC.DNI
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY TC.NOMBRE, YEAR(FECHA_VENTA);

